In [2]:
from fredapi import Fred
fred = Fred(api_key='facfa1b1647b470aa1ab6d747bb53a16')
data = fred.get_series('GDP')

In [3]:
import pandas_datareader.data as web
import datetime
start = datetime.datetime(2020, 1, 1)
end = datetime.datetime(2021, 6, 27)
gdp = web.DataReader('GDP', 'fred', start, end)

In [4]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2020-01-01 to 2021-04-01
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GDP     6 non-null      float64
dtypes: float64(1)
memory usage: 96.0 bytes

In [5]:
gdp.describe()

                GDP
count      6.000000
mean   21600.446833
std     1142.704478
min    19636.731000
25%    21406.329000
50%    21621.369000
75%    22161.564000
max    23046.934000

In [6]:
gdp

                  GDP
DATE
2020-01-01  21538.032
2020-04-01  19636.731
2020-07-01  21362.428
2020-10-01  21704.706
2021-01-01  22313.850
2021-04-01  23046.934

In [7]:
gdp.loc['2021-01-01']

GDP    22313.85
Name: 2021-01-01 00:00:00, dtype: float64

In [10]:
inflation = web.DataReader(['CPIAUCSL', 'CPILFESL'], 'fred', start, end)

In [11]:
inflation

            CPIAUCSL  CPILFESL
DATE
2020-01-01   259.037   266.626
2020-02-01   259.248   267.283
2020-03-01   258.124   267.090
2020-04-01   256.092   265.771
2020-05-01   255.868   265.574
2020-06-01   256.986   265.952
2020-07-01   258.278   267.352
2020-08-01   259.411   268.469
2020-09-01   260.029   268.938
2020-10-01   260.286   269.236
2020-11-01   260.813   269.901
2020-12-01   262.035   270.267
2021-01-01   262.650   270.383
2021-02-01   263.638   270.727
2021-03-01   264.914   271.526
2021-04-01   266.670   273.615
2021-05-01   268.444   275.654
2021-06-01   270.559   277.676

In [13]:
from pandas_datareader import wb
matches = wb.search('gdp.*capita.*const')

In [14]:
matches

,id,name,unit,source,sourceNote,sourceOrganization,topics
691,6.0.GDPpc_constant,"GDP per capita, PPP (constant 2011 internation...",,LAC Equity Lab,GDP per capita based on purchasing power parit...,b'World Development Indicators (World Bank)',Economy & Growth
10629,NY.GDP.PCAP.KD,GDP per capita (constant 2015 US$),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10631,NY.GDP.PCAP.KN,GDP per capita (constant LCU),,World Development Indicators,GDP per capita is gross domestic product divid...,"b'World Bank national accounts data, and OECD ...",Economy & Growth
10633,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2017 internation...",,World Development Indicators,GDP per capita based on purchasing power parit...,"b'International Comparison Program, World Bank...",Economy & Growth
10634,NY.GDP.PCAP.PP.KD.87,"GDP per capita, PPP (constant 1987 internation...",,WDI Database Archives,,b'',

In [15]:
dat = wb.download(indicator='NY.GDP.PCAP.KD', country=['US', 'CA', 'MX'], start=2005, end=2008)

In [16]:
dat

                    NY.GDP.PCAP.KD
country       year
Canada        2008    42063.633052
              2007    42097.435120
              2006    41646.414637
              2005    40989.526824
Mexico        2008     9276.054837
              2007     9288.162478
              2006     9200.402581
              2005     8925.236669
United States 2008    53854.160612
              2007    54299.617241
              2006    53738.091725
              2005    52789.731419

In [17]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 12 entries, ('Canada', '2008') to ('United States', '2005')
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NY.GDP.PCAP.KD  12 non-null     float64
dtypes: float64(1)
memory usage: 565.0+ bytes

In [18]:
import requests
import json
data = requests.get('https://api.stlouisfed.org/fred/series?series_id=GNPCA&api_key=43be4fc471782325cab7d47238bf8962&file_type=json')

In [19]:
data.json()

{'realtime_start': '2023-03-29',
 'realtime_end': '2023-03-29',
 'seriess': [{'id': 'GNPCA',
   'realtime_start': '2023-03-29',
   'realtime_end': '2023-03-29',
   'title': 'Real Gross National Product',
   'observation_start': '1929-01-01',
   'observation_end': '2021-01-01',
   'frequency': 'Annual',
   'frequency_short': 'A',
   'units': 'Billions of Chained 2012 Dollars',
   'units_short': 'Bil. of Chn. 2012 $',
   'seasonal_adjustment': 'Not Seasonally Adjusted',
   'seasonal_adjustment_short': 'NSA',
   'last_updated': '2022-09-29 07:45:54-05',
   'popularity': 18,
   'notes': 'BEA Account Code: A001RX\n\n'}]}

In [22]:
import datapungi_fed as dpf
dpf('gnp').meta

KeyError: 'observations'

In [23]:
!pip install full-fred

Collecting full-fred
  Downloading full_fred-0.0.9a3-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: requests in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from full-fred) (2.28.1)
Requirement already satisfied: pandas in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from full-fred) (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from pandas->full-fred) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from pandas->full-fred) (2022.7.1)
Requirement already satisfied: numpy>=1.18.5 in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from pandas->full-fred) (1.21.5)
Requirement already satisfied: certifi>=2017.4.17 in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from requests->full-fred) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from requests->full-fred) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from requests->full-fred) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from requests->full-fred) (1.26.11)
Requirement already satisfied: six>=1.5 in /Users/taewon/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas->full-fred) (1.16.0)
Installing collected packages: full-fred
Successfully installed full-fred-0.0.9a3

In [24]:
!pytest

============================= test session starts ==============================
platform darwin -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/taewon/금융 데이터 수집
plugins: anyio-3.5.0, html-3.2.0, metadata-2.0.4
collected 0 items

============================ no tests ran in 0.00s =============================

In [28]:
fred.get_series_as_of_date('GDP', '6/1/2019')

     realtime_start       date      value
0        1992-12-22 1946-01-01      199.7
1        1996-01-19 1946-01-01        NaT
2        1997-05-07 1946-01-01      210.4
3        1999-10-28 1946-01-01        NaT
4        1992-12-22 1946-04-01      207.7
...             ...        ...        ...
3017     2018-12-21 2018-07-01  20658.204
3022     2019-02-28 2018-10-01  20891.367
3023     2019-03-28 2018-10-01   20865.14
3028     2019-04-26 2019-01-01  21062.691
3029     2019-05-30 2019-01-01  21048.839

[2906 rows x 3 columns]